import aquariusSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-aquarius-safe-v34.webp'
import ariesSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-aries-safe-v34.webp'
import cancerSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-cancer-safe-v34.webp'
import capricornSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-capricorn-safe-v34.webp'
import geminiSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-gemini-safe-v34.webp'
import leoSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-leo-safe-v34.webp'
import libraSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-libra-safe-v34.webp'
import piscesSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-pisces-safe-v34.webp'
import sagittariusSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-sagittarius-safe-v34.webp'
import scorpioSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-scorpio-safe-v34.webp'
import taurusSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-taurus-safe-v34.webp'
import virgoSrc from '../assets/zodiac/taiwan/local-stories/tw-local-zodiac-virgo-safe-v34.webp'
import type { ArtworkVariant } from '../types'

type LocalSeed = Omit<ArtworkVariant, 'deityId' | 'collectionId' | 'countryCode' | 'culture' | 'subjectKind'> & { subjectId: string }

const local = (seed: LocalSeed): ArtworkVariant => ({
  ...seed,
  deityId: seed.subjectId,
  collectionId: 'taiwan-zodiac-local-stories',
  countryCode: 'TW',
  culture: 'Taiwan',
  subjectKind: 'zodiac',
})

export const TAIWAN_ZODIAC_LOCAL_STORIES_ART: readonly ArtworkVariant[] = [
  local({ id: 'tw-local-zodiac-aries', subjectId: 'aries', zhName: '牡羊座・合歡山晨行', enName: 'Aries · Hehuanshan Dawn', src: ariesSrc, hiddenTaiwan: 'turquoise Taiwan trail-marker enamel', featureLabel: { zh: '合歡山高山杜鵑與雲海', en: 'Hehuanshan rhododendrons and cloud sea' }, featureDescription: { zh: '合歡山是台灣容易親近的高山景觀之一，春季高山杜鵑與日出雲海最具代表性。', en: 'Hehuanshan is known for spring rhododendrons and sunrise cloud seas.' }, portraitFocus: { x: 50, y: 35 }, taiwanHotspot: { x: 78, y: 80, scale: .76, rotation: 0, color: '#20c8c5', accent: '#dfffff' } }),
  local({ id: 'tw-local-zodiac-taurus', subjectId: 'taurus', zhName: '金牛座・阿里山茶作', enName: 'Taurus · Alishan Tea Work', src: taurusSrc, hiddenTaiwan: 'ruby Taiwan tea-basket tag', featureLabel: { zh: '阿里山高山茶與森林鐵路', en: 'Alishan tea and forest railway' }, featureDescription: { zh: '阿里山以高山茶、紅檜森林及穿行山區的森林鐵路形成獨特文化景觀。', en: 'Alishan combines high-mountain tea, red-cypress forests and its mountain railway.' }, portraitFocus: { x: 50, y: 50 }, taiwanHotspot: { x: 76, y: 91, scale: .72, rotation: 0, color: '#cf3e48', accent: '#ffd7d7' } }),
  local({ id: 'tw-local-zodiac-gemini', subjectId: 'gemini', zhName: '雙子座・西門雙城', enName: 'Gemini · Ximending Twins', src: geminiSrc, hiddenTaiwan: 'jade Taiwan crossbody-strap connector', featureLabel: { zh: '西門町街頭文化與機車城市', en: 'Ximending street culture and scooters' }, featureDescription: { zh: '西門町融合行人街區、青年流行文化與台北常見的機車城市景觀。', en: 'Ximending joins pedestrian streets, youth culture and Taipei’s scooter cityscape.' }, portraitFocus: { x: 50, y: 32 }, taiwanHotspot: { x: 51, y: 67, scale: .8, rotation: 0, color: '#47b878', accent: '#e2ffe9' } }),
  local({ id: 'tw-local-zodiac-cancer', subjectId: 'cancer', zhName: '巨蟹座・澎湖潮間', enName: 'Cancer · Penghu Intertidal', src: cancerSrc, hiddenTaiwan: 'coral Taiwan fishing-float mark', featureLabel: { zh: '澎湖玄武岩與石滬', en: 'Penghu basalt and stone fish weirs' }, featureDescription: { zh: '澎湖柱狀玄武岩源自熔岩冷卻，石滬則展現島嶼居民利用潮汐的傳統漁法。', en: 'Penghu’s basalt and stone fish weirs connect volcanic geology with tidal fishing.' }, portraitFocus: { x: 50, y: 50 }, taiwanHotspot: { x: 20, y: 89, scale: .72, rotation: 0, color: '#e26e59', accent: '#ffe1d3' } }),
  local({ id: 'tw-local-zodiac-leo', subjectId: 'leo', zhName: '獅子座・廟埕熱場', enName: 'Leo · Temple Courtyard', src: leoSrc, hiddenTaiwan: 'cobalt Taiwan festival-light panel', featureLabel: { zh: '台灣廟宇剪黏與廟埕文化', en: 'Taiwanese temple ceramics and courtyards' }, featureDescription: { zh: '廟宇屋頂常見剪黏與交趾陶裝飾，廟埕也是節慶、表演與社區交流的重要場所。', en: 'Temple ceramics and courtyards connect craft, festivals and community life.' }, portraitFocus: { x: 50, y: 50 }, taiwanHotspot: { x: 83, y: 90, scale: .7, rotation: 0, color: '#376fe0', accent: '#d8e8ff' } }),
  local({ id: 'tw-local-zodiac-virgo', subjectId: 'virgo', zhName: '處女座・池上稻日', enName: 'Virgo · Chishang Rice Day', src: virgoSrc, hiddenTaiwan: 'violet Taiwan field-notebook patch', featureLabel: { zh: '池上稻田與灌溉地景', en: 'Chishang rice and irrigation landscape' }, featureDescription: { zh: '池上以縱谷水源、稻田與灌溉渠道形成開闊農業地景。', en: 'Valley water, rice fields and irrigation channels shape Chishang.' }, portraitFocus: { x: 50, y: 30 }, taiwanHotspot: { x: 52, y: 75, scale: .78, rotation: 0, color: '#9362dd', accent: '#efe2ff' } }),
  local({ id: 'tw-local-zodiac-libra', subjectId: 'libra', zhName: '天秤座・大稻埕暮光', enName: 'Libra · Dadaocheng Twilight', src: libraSrc, hiddenTaiwan: 'emerald Taiwan balance counterweight', featureLabel: { zh: '大稻埕茶業、街屋與碼頭', en: 'Dadaocheng tea, shophouses and wharf' }, featureDescription: { zh: '大稻埕因茶葉與布匹貿易興盛，紅磚街屋及淡水河碼頭仍保留城市發展痕跡。', en: 'Tea trade, red-brick shophouses and the wharf trace Dadaocheng’s growth.' }, portraitFocus: { x: 50, y: 30 }, taiwanHotspot: { x: 49, y: 79, scale: .8, rotation: 0, color: '#2ca36a', accent: '#e4ffe7' } }),
  local({ id: 'tw-local-zodiac-scorpio', subjectId: 'scorpio', zhName: '天蠍座・太魯閣雨行', enName: 'Scorpio · Taroko Rain', src: scorpioSrc, hiddenTaiwan: 'amber Taiwan trail-marker inlay', featureLabel: { zh: '太魯閣大理岩峽谷', en: 'Taroko marble gorge' }, featureDescription: { zh: '太魯閣峽谷由河流長期下切抬升中的大理岩地層，形成陡峭岩壁與湍急溪流。', en: 'Taroko Gorge formed as rivers cut through uplifting marble.' }, portraitFocus: { x: 50, y: 45 }, taiwanHotspot: { x: 78, y: 84, scale: .72, rotation: 0, color: '#e99b2e', accent: '#fff0c9' } }),
  local({ id: 'tw-local-zodiac-sagittarius', subjectId: 'sagittarius', zhName: '射手座・玉山追光', enName: 'Sagittarius · Yushan Light', src: sagittariusSrc, hiddenTaiwan: 'crimson Taiwan bow-case clasp', featureLabel: { zh: '玉山主峰與台灣藍鵲', en: 'Yushan and the Taiwan blue magpie' }, featureDescription: { zh: '玉山是台灣最高峰；台灣藍鵲是以鮮明藍羽聞名的特有種鳥類。', en: 'Yushan is Taiwan’s highest peak; the Taiwan blue magpie is an endemic bird.' }, portraitFocus: { x: 50, y: 30 }, taiwanHotspot: { x: 44, y: 67, scale: .8, rotation: 0, color: '#c93643', accent: '#ffe0df' } }),
  local({ id: 'tw-local-zodiac-capricorn', subjectId: 'capricorn', zhName: '摩羯座・清水斷崖', enName: 'Capricorn · Qingshui Cliff', src: capricornSrc, hiddenTaiwan: 'turquoise Taiwan railway-signal panel', featureLabel: { zh: '清水斷崖與海岸鐵路', en: 'Qingshui Cliff and coastal railway' }, featureDescription: { zh: '清水斷崖讓中央山脈直接臨接太平洋，鐵路沿山海狹帶穿行。', en: 'At Qingshui Cliff the Central Range meets the Pacific beside a coastal railway.' }, portraitFocus: { x: 50, y: 30 }, taiwanHotspot: { x: 82, y: 76, scale: .76, rotation: 0, color: '#26bbb4', accent: '#dbffff' } }),
  local({ id: 'tw-local-zodiac-aquarius', subjectId: 'aquarius', zhName: '水瓶座・九份雨夜', enName: 'Aquarius · Jiufen Rain', src: aquariusSrc, hiddenTaiwan: 'gold Taiwan ceramic-vessel relief', featureLabel: { zh: '九份山城與台灣陶藝', en: 'Jiufen hillside and Taiwanese ceramics' }, featureDescription: { zh: '九份沿山坡發展出密集階梯巷弄，現代陶藝延續台灣在地手作。', en: 'Jiufen stair lanes meet contemporary Taiwanese ceramic craft.' }, portraitFocus: { x: 50, y: 30 }, taiwanHotspot: { x: 45, y: 77, scale: .76, rotation: 0, color: '#d9aa38', accent: '#fff2bd' } }),
  local({ id: 'tw-local-zodiac-pisces', subjectId: 'pisces', zhName: '雙魚座・東岸月浪', enName: 'Pisces · East Coast Moon Current', src: piscesSrc, hiddenTaiwan: 'magenta Taiwan glass current marker', featureLabel: { zh: '東海岸與黑潮', en: 'Taiwan’s east coast and Kuroshio' }, featureDescription: { zh: '黑潮沿台灣東側北上，帶來溫暖海水與豐富海洋生態。', en: 'The Kuroshio flows north along Taiwan’s east coast, carrying warm water and marine life.' }, portraitFocus: { x: 50, y: 30 }, taiwanHotspot: { x: 49, y: 83, scale: .76, rotation: 0, color: '#d64b9c', accent: '#ffe1f4' } }),
]
